In [1]:
import numpy as np

In [2]:
#1 Create a 5 × 5 NumPy matrix containing numbers from 1 to 25 and print: 
# ○ The first row 
# ○ The last column 
# ○ The diagonal elements 

a=np.arange(1,26).reshape(5,5)
print(a)
print(a[0])
print(a[:,-1])
print(np.diag(a))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[ 1  7 13 19 25]


In [3]:
#2 Create two 3 × 3 matrices and perform matrix addition, subtraction, and matrix multiplication.

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])

print(a+b)
print(a-b)
print(a@b)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [4]:
#3Create a NumPy array of numbers from 1 to 100 and print all numbers divisible by 3 using Boolean indexing. 

a=np.arange(1,101)
print(a[a%3==0])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [5]:
#4 Create a 4 × 4 matrix and replace all even numbers with 0. 

a=np.arange(1,17).reshape(4,4)
a[a%2==0]=0
print(a)

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [6]:
#5 Create a 5 × 5 matrix of random integers and find: 
# ○ Maximum value 
# ○ Minimum value 
# ○ Mean 
# ○ Median 


a=np.random.randint(1,100,(5,5))
print(a)
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.median(a))

[[52 76  8 42 94]
 [62 73 63 41 20]
 [21 62 58 19  7]
 [48  5 62  2 16]
 [89  9 81 22  8]]
94
2
41.6
42.0


In [7]:
#6 Create a NumPy array containing 20 random numbers and sort it in ascending and descending order. 



a=np.random.randint(1,100,20)
print(np.sort(a))
print(np.sort(a)[::-1])

[ 6 12 16 19 22 24 29 32 35 40 44 52 56 63 64 68 72 82 83 85]
[85 83 82 72 68 64 63 56 52 44 40 35 32 29 24 22 19 16 12  6]


In [8]:
#7 Create a 6 × 6 matrix and print: 
# ○ Main diagonal 
# ○ Upper triangular part 
# ○ Lower triangular part 
 

a=np.arange(1,37).reshape(6,6)
print(np.diag(a))
print(np.triu(a))
print(np.tril(a))

[ 1  8 15 22 29 36]
[[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
[[ 1  0  0  0  0  0]
 [ 7  8  0  0  0  0]
 [13 14 15  0  0  0]
 [19 20 21 22  0  0]
 [25 26 27 28 29  0]
 [31 32 33 34 35 36]]


In [9]:
#8 Create a NumPy array of 20 elements and reshape it into: 
# ○ 4 × 5 matrix 
# ○ 2 × 10 matrix 
# ○ 5 × 4 matrix 


a=np.arange(1,21)
print(a.reshape(4,5))
print(a.reshape(2,10))
print(a.reshape(5,4))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [10]:
#9 Create a 5 × 5 matrix and calculate the sum of: 
# ○ Each row 
# ○ Each column 


a=np.arange(1,26).reshape(5,5)
print(np.sum(a,axis=1))
print(np.sum(a,axis=0))

[ 15  40  65  90 115]
[55 60 65 70 75]


In [11]:
#10 Create two arrays and find all common elements between them. 


a=np.array([1,2,3,4,5,6])
b=np.array([4,5,6,7,8,9])

print(np.intersect1d(a,b))

[4 5 6]


In [12]:
#11 Create a 5 × 5 matrix and find the position (row and column index) of the largest element. 


a=np.random.randint(1,100,(5,5))
print(a)

p=np.unravel_index(np.argmax(a),a.shape)
print(p)

[[87 32 58 27 59]
 [82  1 61 46 50]
 [87 60 33 77 65]
 [34 35 56 65 93]
 [27 76 53 81  4]]
(np.int64(3), np.int64(4))


In [13]:
#12 Create a dataset of students' marks using a NumPy array and find: 
# ● Highest marks 
# ● Lowest marks 
# ● Average marks
# ● Students scoring above average 

m=np.array([78,65,92,88,55,70,95,81])

print(np.max(m))
print(np.min(m))
print(np.mean(m))
print(m[m>np.mean(m)])

95
55
78.0
[92 88 95 81]
